#!/bin/bash

while getopts u:d:p:f: option

do

	case "${option}"

		in

		u) USER=${OPTARG};;

		d) DATE=${OPTARG};;

		p) PRODUCT=${OPTARG};;

		f) FORMAT=${OPTARG};;

	esac

done

echo "USER=$USER"
echo "DATE=$DATE"
echo "PRODUCT=$PRODUCT"
echo "FORMAT=$FORMAT"
